[workspace]
members = ["katori-gui", "gdbadapter"]

[package]
name = "katori"
version = "0.1.0"
edition = "2021"

[dependencies]
katori-gui = { path = "katori-gui" }
gdbadapter = { path = "gdbadapter" }
tokio = { version = "1.0", features = ["full"] }
log = "0.4"
simple_logger = "4.3"
